import crypto from "crypto"
import { prisma } from "@/lib/db/prisma"
// import { generateCourseFromN8n } from "@/lib/n8n"
import { AppError } from "@/lib/errors"

export type CourseMode = "beginner" | "simplified" | "quick"

/**
 * Service handling all course generation and retrieval business logic.
 */
export const courseService = {
  /**
   * Resolves the course generated by n8n.
   * Because n8n writes the course to the database directly, we query for the latest course
   * created after the session started, which the user is enrolled in.
   * This is a temporary strategy until a queue/webhook system is fully implemented.
   *
   * @param userId - The user ID
   * @param sessionCreatedAt - The time the chat session started
   * @returns The generated course ID
   */
  async resolveGeneratedCourse(userId: string, sessionCreatedAt: Date): Promise<string> {
    const course = await prisma.course.findFirst({
      where: {
        createdAt: { gte: sessionCreatedAt },
        enrollments: { some: { userId } },
      },
      orderBy: { createdAt: 'desc' },
    });

    if (!course) {
      throw new AppError(
        'Generated course not found in database',
        404,
        'COURSE_NOT_FOUND'
      );
    }

    return course.id;
  },

  /**
   * Enrolls a user in a course if they are not already enrolled.
   */
  async enrollUser(userId: string, courseId: string) {
    const existingEnrollment = await prisma.enrollment.findUnique({
      where: {
        userId_courseId: { userId, courseId },
      },
    });

    if (!existingEnrollment) {
      await prisma.enrollment.create({
        data: {
          userId,
          courseId,
        },
      });
    }
  },

  /**
   * Retrieves all courses a user is enrolled in.
   *
   * @param userId - The authenticated user's ID
   * @returns Array of mapped courses suitable for frontend display
   */
  async getUserCourses(userId: string) {
    const enrollments = await prisma.enrollment.findMany({
      where: { userId },
      include: {
        course: {
          include: {
            modules: {
              where: { deletedAt: null },
              include: { chapters: { orderBy: { sortNo: "asc" } } },
              orderBy: { sortNo: "asc" }
            }
          }
        }
      },
      orderBy: { lastAccessedAt: "desc" }
    });

    return enrollments.map(mapEnrollmentToCourse);
  },

  /**
   * Retrieves a single course a user is enrolled in.
   *
   * @param userId - The authenticated user's ID
   * @param courseId - The course ID
   * @returns Mapped course suitable for frontend display
   */
  async getCourseByEnrollment(userId: string, courseId: string) {
    const enrollment = await prisma.enrollment.findUnique({
      where: { userId_courseId: { userId, courseId } },
      include: {
        course: {
          include: {
            modules: {
              where: { deletedAt: null },
              include: { chapters: { orderBy: { sortNo: "asc" } } },
              orderBy: { sortNo: "asc" }
            }
          }
        }
      }
    });

    if (!enrollment) {
      throw new AppError("Course not found or user not enrolled", 404, "NOT_FOUND");
    }

    return mapEnrollmentToCourse(enrollment);
  }
};

/**
 * Helper to map Prisma enrollment+course data to the frontend Course interface.
 */
function mapEnrollmentToCourse(enrollment: any) {
  const course = enrollment.course;
  let totalPages = 0;
  let totalEstimatedMinutes = 0;
  
  const mappedModules = course.modules.map((mod: any) => {
    const pages = mod.chapters.map((chapter: any) => {
      let blocks = [];
      try {
        if (chapter.content) {
          const parsed = JSON.parse(chapter.content);
          if (Array.isArray(parsed)) {
            blocks = parsed;
          } else {
            blocks = [{ id: `${chapter.id}-content`, type: 'text', content: chapter.content }];
          }
        }
      } catch (e) {
        // Fallback for when content is raw markdown instead of stringified JSON
        if (chapter.content) {
          blocks = [{ id: `${chapter.id}-content`, type: 'text', content: chapter.content }];
        }
      }
      return {
        id: chapter.id,
        title: chapter.title,
        blocks,
        estimatedMinutes: 5
      };
    });
    
    totalPages += pages.length;
    totalEstimatedMinutes += pages.length * 5;

    return {
      id: mod.id,
      title: mod.title,
      description: "Module description",
      pages,
      estimatedMinutes: pages.length * 5,
      contentTypes: ["text"],
      hasQuiz: false
    };
  });

  return {
    id: course.id,
    topic: course.topic,
    title: course.title,
    description: course.description || "",
    mode: course.mode,
    status: enrollment.status,
    modules: mappedModules,
    totalEstimatedMinutes,
    totalPages,
    createdAt: course.createdAt.toISOString(),
    lastAccessedAt: enrollment.lastAccessedAt.toISOString(),
    completedPages: Math.floor(totalPages * (enrollment.completionPct / 100)),
    xpEarned: 0
  };
}
