/* ============================================================
   Course Types
   Defines the shape of courses, modules, pages, and content
   blocks returned by the n8n course generation API.
   ============================================================ */

/** The three learning modes that determine course structure and UX pace */
export type LearningMode = 'beginner' | 'simplified' | 'quick';

/** Tracks where a course stands in the user's journey */
export type CourseStatus = 'generating' | 'ready' | 'in_progress' | 'completed';

/**
 * Content block types that can appear on a learning page.
 * ContentRenderer detects the type and renders the correct component.
 */
export type ContentBlockType = 'text' | 'bullet_list' | 'code' | 'math' | 'video' | 'image';

/**
 * A single content block within a learning page.
 * Each page is composed of one or more blocks rendered sequentially.
 */
export interface ContentBlock {
  /** Unique identifier for the block */
  id: string;
  /** Determines which renderer component is used */
  type: ContentBlockType;
  /** The raw content — markdown text, code string, LaTeX expression, or video URL */
  content: string;
  /** Optional metadata — language for code blocks, video title, etc. */
  meta?: {
    /** Programming language for syntax highlighting (code blocks) */
    language?: string;
    /** Video title for accessibility (video blocks) */
    title?: string;
    /** YouTube video ID (video blocks) */
    videoId?: string;
    /** Alt text for images */
    alt?: string;
  };
}

/**
 * A single page within a module.
 * Users swipe between pages in the learning interface.
 */
export interface CoursePage {
  /** Unique identifier for the page */
  id: string;
  /** Page title displayed at the top of the learning interface */
  title: string;
  /** Ordered list of content blocks that compose this page */
  blocks: ContentBlock[];
  /** Estimated reading/viewing time in minutes */
  estimatedMinutes: number;
}

/**
 * A module groups related pages together.
 * Quizzes may appear after module completion depending on learning mode.
 */
export interface Module {
  /** Unique identifier for the module */
  id: string;
  /** Module title shown in the learning plan */
  title: string;
  /** Brief description of what this module covers */
  description: string;
  /** Ordered list of pages within this module */
  pages: CoursePage[];
  /** Estimated total time for all pages in minutes */
  estimatedMinutes: number;
  /** Content type indicators for the learning plan UI */
  contentTypes: ContentBlockType[];
  /** Whether a quiz should appear after completing this module */
  hasQuiz: boolean;
  /** Optional YouTube video lecture URL */
  youtubeUrl?: string;
}

/**
 * A complete course generated by the AI.
 * Contains all modules, metadata, and progress tracking.
 */
export interface Course {
  /** Unique identifier — used in URL: /learn/[courseId] */
  id: string;
  /** The topic the user requested to learn */
  topic: string;
  /** Course title generated by the AI */
  title: string;
  /** Brief course description */
  description: string;
  /** The learning mode selected by the user */
  mode: LearningMode;
  /** Current status of the course */
  status: CourseStatus;
  /** Ordered list of modules */
  modules: Module[];
  /** Total estimated time in minutes */
  totalEstimatedMinutes: number;
  /** Total number of pages across all modules */
  totalPages: number;
  /** ISO timestamp of when the course was created */
  createdAt: string;
  /** ISO timestamp of last access */
  lastAccessedAt: string;
  /** Number of completed pages (for progress tracking) */
  completedPages: number;
  /** Arrays of exactly which chapters and modules have been completed */
  completedChapterIds: string[];
  completedModuleIds: string[];
  /** XP earned from this course so far */
  xpEarned: number;
}

/**
 * Request body sent to the n8n webhook for course generation.
 */
export interface CourseGenerationRequest {
  /** What the user wants to learn */
  topic: string;
  /** Selected learning mode */
  mode: LearningMode;
  /** Current user ID for personalization */
  userId: string;
}

/**
 * Response from the n8n webhook after course generation.
 */
export interface CourseGenerationResponse {
  /** Whether the generation was successful */
  success: boolean;
  /** The generated course data */
  course?: Course;
  /** Error message if generation failed */
  error?: string;
}
