/* ============================================================
   Type Definitions — Course System
   Types for courses, modules, pages, and learning modes.
   ============================================================ */

import type { QuizQuestion } from "./quiz";

/** The three learning modes that determine course UX */
export type LearningMode = "beginner" | "simplified" | "quick";

/** Content block types that can appear in a learning page */
export type ContentBlockType =
  | "text"
  | "bullet-list"
  | "code"
  | "math"
  | "video"
  | "image";

/** A single content block within a learning page */
export interface ContentBlock {
  id: string;
  type: ContentBlockType;
  content: string;
  /** Language for code blocks (e.g. "python", "typescript") */
  language?: string;
  /** Video URL for video blocks */
  videoUrl?: string;
  /** Alt text for image blocks */
  alt?: string;
}

/** A single page within a module — the atomic learning unit */
export interface CoursePage {
  id: string;
  title: string;
  content: ContentBlock[];
  /** Order index within the module (0-based) */
  order: number;
}


/** A module — a grouped section of the course */
export interface CourseModule {
  id: string;
  title: string;
  /** Estimated time in minutes */
  estimatedTime: number;
  pages: CoursePage[];
  quiz?: QuizQuestion[];
  /** Content type icons to display (e.g. ["text", "code", "video"]) */
  contentTypes: ContentBlockType[];
  order: number;
}

/** A complete course generated by the AI */
export interface Course {
  id: string;
  title: string;
  topic: string;
  mode: LearningMode;
  modules: CourseModule[];
  /** Total estimated time in minutes */
  totalTime: number;
  /** ISO date string */
  createdAt: string;
  /** ISO date string of last access */
  lastAccessedAt: string;
  /** Completion percentage 0-100 */
  progress: number;
  /** Current module index */
  currentModuleIndex: number;
  /** Current page index within the current module */
  currentPageIndex: number;
  /** Whether the course is fully completed */
  isCompleted: boolean;
  /** XP earned from this course so far */
  xpEarned: number;
}

/** Summary version of a course for list views */
export interface CourseSummary {
  id: string;
  title: string;
  mode: LearningMode;
  progress: number;
  lastAccessedAt: string;
  isCompleted: boolean;
  totalModules: number;
}

/** Learning mode display configuration */
export interface LearningModeConfig {
  name: string;
  mode: LearningMode;
  description: string;
  estimatedTime: string;
  color: string;
  icon: string;
}
